include('shared.lua')
 
ENT.RenderGroup = RENDERGROUP_BOTH
 
function ENT:Draw()
 
    self:DrawModel()
     
end
 
function ENT:DrawTranslucent()
 
    self:Draw()
     
end

local function ShowShop( data )

	ShowShopDerma()
	 
end
usermessage.Hook( "ShowShop", ShowShop );

local function ShowHint( data )

	hint = data:ReadString()
	GAMEMODE:AddNotify(hint, NOTIFY_GENERIC, 5)
	
end
usermessage.Hook( "ShowHint", ShowHint)

function ShowShopDerma()

-- Lua generated by DermaDesigner

local DButton18
local DButton19
local DButton20
local DButton21
local DButton22
local DButton17
local DButton16
local DButton15
local DNumberWang1
local purchAmmoPistol
local purchGrenade
local purchAR2
local DLabel2
local purchSMG
local DButton17PZQU
local purch357
local DButton16VHKB
local purchCrowbar
local purchPistol
local WeapShopWelcome
local DPanel2
local WeapShopFrame

WeapShopFrame = vgui.Create('DFrame')
WeapShopFrame:SetSize(519, 359)
WeapShopFrame:Center()
WeapShopFrame:SetTitle('Supply Shop')
WeapShopFrame:MakePopup()

DPanel2 = vgui.Create('DPanel')
DPanel2:SetParent(WeapShopFrame)
DPanel2:SetSize(509, 326)
DPanel2:SetPos(5, 27)

WeapShopWelcome = vgui.Create('DLabel')
WeapShopWelcome:SetParent(DPanel2)
WeapShopWelcome:SetPos(86, 6)
WeapShopWelcome:SetText('Welcome to the Supply Shop Please Click on a Button to purchase.')
WeapShopWelcome:SizeToContents()
WeapShopWelcome:SetTextColor(Color(0, 0, 0, 255))
purchPistol = vgui.Create('DButton')
purchPistol:SetParent(DPanel2)
purchPistol:SetSize(228, 20)
purchPistol:SetPos(7, 67)
purchPistol:SetText('Purchase A Pistol for 100 credits')
purchPistol.DoClick = function() RunConsoleCommand("purchWeapon", "weapon_pistol") end

purchCrowbar = vgui.Create('DButton')
purchCrowbar:SetParent(DPanel2)
purchCrowbar:SetSize(228, 20)
purchCrowbar:SetPos(7, 43)
purchCrowbar:SetText('Purchase A Crowbar for 50 credits')
purchCrowbar.DoClick = function() RunConsoleCommand("purchWeapon", "weapon_crowbar") end

DButton16VHKB = vgui.Create('DButton')
DButton16VHKB:SetParent(DPanel2)
DButton16VHKB:SetSize(228, 20)
DButton16VHKB:SetPos(8, 206)
DButton16VHKB:SetText('Purchase Portable Health Kit for 30 Credits.')
DButton16VHKB.DoClick = function() RunConsoleCommand("purchWeapon", "weapon_healthkit") end

purch357 = vgui.Create('DButton')
purch357:SetParent(DPanel2)
purch357:SetSize(228, 20)
purch357:SetPos(7, 91)
purch357:SetText('Purchase A .357 Handgun for 200 credits.')
purch357.DoClick = function() RunConsoleCommand("purchWeapon", "weapon_357") end

purchSMG = vgui.Create('DButton')
purchSMG:SetParent(DPanel2)
purchSMG:SetSize(228, 20)
purchSMG:SetPos(7, 138)
purchSMG:SetText('Purchase an SMG for 300 credits.')
purchSMG.DoClick = function() RunConsoleCommand("purchWeapon", "weapon_smg1") end

DButton17PZQU = vgui.Create('DButton')
DButton17PZQU:SetParent(DPanel2)
DButton17PZQU:SetSize(245, 20)
DButton17PZQU:SetPos(10, 255)
DButton17PZQU:SetText('Hire Assistant Fighter for 500 Credits Per Level.')
DButton17PZQU.DoClick =  function() RunConsoleCommand("hireNPC", DNumberWang1:GetValue()) end

purchAR2 = vgui.Create('DButton')
purchAR2:SetParent(DPanel2)
purchAR2:SetSize(228, 20)
purchAR2:SetPos(7, 161)
purchAR2:SetText('Purchase AR2 for 500 credits.')
purchAR2.DoClick = function() RunConsoleCommand("purchWeapon", "weapon_ar2") end

purchAmmoPistol = vgui.Create('DButton')
purchAmmoPistol:SetParent(DPanel2)
purchAmmoPistol:SetSize(235, 20)
purchAmmoPistol:SetPos(266, 43)
purchAmmoPistol:SetText('Purchase 20 Pistol Rounds for 10 Credits')
purchAmmoPistol.DoClick = function() RunConsoleCommand("purchAmmo", "Pistol") end

purchGrenade = vgui.Create('DButton')
purchGrenade:SetParent(DPanel2)
purchGrenade:SetSize(228, 20)
purchGrenade:SetPos(7, 114)
purchGrenade:SetText('Purchase A Grenade for 250 credits.')
purchGrenade.DoClick = function() RunConsoleCommand("purchWeapon", "weapon_frag") end

DButton15 = vgui.Create('DButton')
DButton15:SetParent(DPanel2)
DButton15:SetSize(236, 20)
DButton15:SetPos(266, 67)
DButton15:SetText('Purchase 10 .357 Rounds for 15 Credits')
DButton15.DoClick = function() RunConsoleCommand("purchAmmo", "357") end

DButton16 = vgui.Create('DButton')
DButton16:SetParent(DPanel2)
DButton16:SetSize(236, 20)
DButton16:SetPos(266, 91)
DButton16:SetText('Purchase 8 Buckshot Rounds for 5 Credits')
DButton16.DoClick = function() RunConsoleCommand("purchAmmo", "Buckshot") end

DButton17 = vgui.Create('DButton')
DButton17:SetParent(DPanel2)
DButton17:SetSize(236, 19)
DButton17:SetPos(266, 114)
DButton17:SetText('Purchase 20 SMG Rounds for 20 Credits.')
DButton17.DoClick = function() RunConsoleCommand("purchAmmo", "SMG1") end

DButton22 = vgui.Create('DButton')
DButton22:SetParent(DPanel2)
DButton22:SetSize(236, 20)
DButton22:SetPos(266, 228)
DButton22:SetText('Purchase 1 AR2 Ball for 600 Credits.')
DButton22.DoClick = function() RunConsoleCommand("purchAmmo", "AR2AltFire") end

DButton21 = vgui.Create('DButton')
DButton21:SetParent(DPanel2)
DButton21:SetSize(236, 20)
DButton21:SetPos(266, 205)
DButton21:SetText('Purchase 1 SMG Grenade for 150 Credits')
DButton21.DoClick = function() RunConsoleCommand("purchAmmo", "SMG1_Grenade") end

DButton20 = vgui.Create('DButton')
DButton20:SetParent(DPanel2)
DButton20:SetSize(236, 20)
DButton20:SetPos(266, 182)
DButton20:SetText('Purchase 1 RPG Round for 300 Credits')
DButton20.DoClick = function() RunConsoleCommand("purchAmmo", "RPG_Round") end

DButton19 = vgui.Create('DButton')
DButton19:SetParent(DPanel2)
DButton19:SetSize(236, 20)
DButton19:SetPos(266, 159)
DButton19:SetText('Purchase 5 Crossbow Bolts for 100 Credits')
DButton19.DoClick = function() RunConsoleCommand("purchAmmo", "XBowBolt") end

DButton18 = vgui.Create('DButton')
DButton18:SetParent(DPanel2)
DButton18:SetSize(236, 20)
DButton18:SetPos(266, 136)
DButton18:SetText('Purchase 20 AR2 Rounds for 30 Credits')
DButton18.DoClick = function() RunConsoleCommand("purchAmmo", "AR2") end

DLabel2 = vgui.Create('DLabel')
DLabel2:SetParent(DPanel2)
DLabel2:SetPos(10, 236)
DLabel2:SetText('Assistant Level: ')
DLabel2:SizeToContents()
DLabel2:SetTextColor(Color(0, 0, 0, 255))
DNumberWang1 = vgui.Create('DNumberWang')
DNumberWang1:SetParent(DPanel2)
DNumberWang1:SetPos(91, 232)
DNumberWang1:SetDecimals(0)
DNumberWang1:SetFloatValue(0)
DNumberWang1:SetFraction(0)
DNumberWang1.OnMouseReleased = function() end
DNumberWang1.OnValueChanged = function() end
DNumberWang1:SetValue('1')
DNumberWang1:SetMinMax( 1, 198)

end